language: java
os: linux
jdk:
  - openjdk8

branches:
  only:
    - master
    - develop

before_install:
  - chmod +x ./gradlew

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'

notifications:
  webhooks:
    urls:
      - $WEBHOOK_URL
    on_success: always
    on_failure: always
    on_start:   always
    on_cancel:  always
    on_error: always
  email:
    recipients:
      - $EMAIL
    on_success: always
    on_failure: always
    on_start:   always
    on_cancel:  always
    on_error: always